---

- name: Desktop and laptop playbook
  hosts: all
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - htop
          - cronie
          - keepass
          - nextcloud-client
          - steam
          - cura
          - code
          - lutris
          - wine

    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dest: /home/zanbee/.bashrc
        owner: zanbee
        group: zanbee
    
    - name: auto provision
      include_tasks: tasks/auto_provision.yml

    - name: set wallpaper
      include_tasks: tasks/wallpaper.yml

    - name: keepass plugins
      include_tasks: tasks/keepass.yml