---

- name: Desktop and laptop playbook
  hosts: localhost
  connection: local
  become: true
  
  vars_files:
    - vars/secrets.yml

  tasks:
    - name: echo email
      debug: 
        msg:  echo "{{ email }}"   
    - include_tasks: tasks/odin/main.yml
      when: "'Odin' in ansible_hostname" 
