---

- name: Desktop and laptop playbook
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name: 
          - htop
          - cronie
          - keepass
          - nextcloud-client
          - steam
          - cura
          - code
          - lutris
          - wine

    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dest: /home/zanbee/.bashrc
        owner: zanbee
        group: zanbee

    - name: copy wallpaper folder
      copy:
        src: files/salientos/
        dest: /usr/share/endeavouros/backgrounds/salientos
        owner: root
        group: root

    - name: set wallpaper
      xfconf:
        channel: "xfce4-desktop"
        property: "/backdrop/screen0/monitorDVI-D-1/workspace0/last-image"
        value_type: string
        value: "/usr/share/endeavouros/backgrounds/salientos/01.jpg"
      become_user: zanbee
      become: true
      environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus

    - name: set changing wallpaper
      become_user: zanbee
      xfconf:
        channel: "xfce4-desktop"
        property: "/backdrop/screen0/monitorDVI-D-1/workspace0/backdrop-cycle-enable"
        value_type: bool
        value: "true"
      become_user: zanbee
      become: true
      environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus

    - name: set random wallpaper
      become_user: zanbee
      xfconf:
        channel: "xfce4-desktop"
        property: "/backdrop/screen0/monitorDVI-D-1/workspace0/backdrop-cycle-random-order"
        value_type: bool
        value: "true"
      become_user: zanbee
      become: true
      environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus

    - name: add ansible user
      user:
        name: vor
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_vor
        dest: /etc/sudoers.d/vor
        owner: root
        group: root
        mode: 0440
  
    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: vor
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/MVrauwdeunt/ansible_desktop.git

    - name: get URL 
      uri:                                                               
        url: https://api.github.com/repos/kee-org/keepassrpc/releases/latest
        return_content: true                                             
      register: json_reponse                                             

    - name: download 
      unarchive:                                                           
        url: "{{ json_reponse.json.zipball_url }}"                       
        dest: /home/zanbee/keepassrpc.plgx      