---

- name: Desktop and laptop playbook
  hosts: localhost
  connection: local
  become: true

  tasks:
    - debug: ansible_hostname
    - include_tasks: tasks/odin/main.yml
      when: "'Odin' in ansible_hostname" 
