---

- name: Desktop and laptop playbook
  hosts: localhost
  connection: local
  become: true
  
  vars_files:
    - vars/secrets.yml

  vars:
    ansible_become_pass: '{{ su_password }}'

  tasks:
    - include_tasks: tasks/odin/main.yml
      #when: "'Odin' in ansible_hostname" 
