---

- name: Desktop and laptop playbook
  hosts: localhost
  connection: local
  become: true

  tasks:
    - import_playbook: tasks/packages.yml
    - import_playbook: tasks/wallpaper.yml
    - import_playbook: tasks/configuration.yml
    - import_playbook: tasks/auto_provision.yml