---
  - name: install packages
    package:
      name: 
        - htop
        - cronie
        - keepass
        - vim
        - cura
        - code
        - thunderbird
        - nextcloud-client
        - libreoffice-fresh
        - steam
        - lutris
        - steam
        - wine
        - powerline-fonts
  
  - name: Clone a github repository
    git:
      repo: https://github.com/andresgongora/synth-shell.git
      dest: /home/zanbee/synth-shell
      clone: yes
      update: yes

  - name: check permission
    ansible.builtin.file:
      path: /home/zanbee/synth-shell/setup.sh
      mode: +x
