---
  - name: install packages
    package:
      name: 
        - htop
        - cronie
        - keepass
        - vim
        - cura
        - code
        - thunderbird
        - nextcloud-client
        - libreoffice-fress
        - lutris
        - steam
        - wine
