---
  - name: install packages
    package:
      name: 
        - htop
        - cronie
        - keepass
        - vim
        - cura
        - code
        - thunderbird
        - nextcloud-client
        - libreoffice-fresh
        - steam
        - lutris
        - steam
        - wine
        - powerline-fonts
        - bc
        - xsel
        - xdotool
  
  - name: Clone Synth-Shell github repository
    git:
      repo: https://github.com/andresgongora/synth-shell.git
      dest: /home/zanbee/synth-shell
      clone: yes
      update: yes

  - name: Set Permission 
    ansible.builtin.file:
      path: /home/zanbee/synth-shell/setup.sh
      mode: +x

  #- name: Run setup scruipt
  #  ansible.builtin.script: /home/zanbee/synth-shell/setup.sh
